MODULE Defs
IMPLICIT NONE

INTEGER, PARAMETER, PUBLIC :: SP = SELECTED_REAL_KIND(6,30)
INTEGER, PARAMETER, PUBLIC :: DP = SELECTED_REAL_KIND(12,60)
INTEGER, PARAMETER, PUBLIC :: QP = SELECTED_REAL_KIND(24,60)
INTEGER, PARAMETER, PUBLIC :: I4B = SELECTED_INT_KIND(9)
INTEGER, PARAMETER, PUBLIC :: I8B = SELECTED_INT_KIND(12)
INTEGER, PARAMETER, PUBLIC :: LGT = KIND(.TRUE.)

REAL(DP), PARAMETER, PUBLIC :: pi = 3.1415926535897932_dp
REAL(DP), PARAMETER, PUBLIC :: conv = 197.327054064_dp
REAL(DP), PARAMETER, PUBLIC :: conv2 = .197327054064_dp

COMPLEX(DP), PARAMETER, PUBLIC :: ic = (0._dp,1._dp)

CHARACTER(80), PARAMETER, PUBLIC :: stars = '________________________________________________________________________________'

END MODULE Defs
